package reverse;
// Generated 18 nov 2022 17:57:03 by Hibernate Tools 6.1.3.Final

/**
 * Listaempleados generated by hbm2java
 */
public class Listaempleados implements java.io.Serializable {

	private ListaempleadosId id;

	public Listaempleados() {
	}

	public Listaempleados(ListaempleadosId id) {
		this.id = id;
	}

	public ListaempleadosId getId() {
		return this.id;
	}

	public void setId(ListaempleadosId id) {
		this.id = id;
	}

}
